### ISSUE TITLE
Unable to run from battery with SIM868/SIM7070G

### ISSUE THREAD

**Issue by whitesmokepcb** [Xinyuan-LilyGO/LilyGo-T-PCIE#11]
There is an issue with running LilyGo-T-PCIE with SIM868/SIM7070G with lithium 3.68V battery. 
When connected to USB 3.x board run OK. 

-Tested lot of combinations batteries on 3,6-3,7V (2xDcell spiral, 4xDcell spiral, that can run >6A continuously, 2xD cell bobbin with additional super cap 3A, lipo rechargeable 3,7V), no chance to run this board with SIM868 PCIE card on battery and 5-6 boards and modems whiteout success. There is some issue with A192 and regulating of voltage. When connect USB with 5V everything run well.
->on 3,3V pin there is constant 3.270V till 3.292V voltage. So voltage is stable.

-Tested also with 2 different laboratory programmable DC power supply (RIGOL DP832/1308A), even set 4.1V on battery connector still unable to run SIM868 PCIE board. Also tested to power 3.3V pins with 3.3-3.7V, whiteout success.

So please, what is the best option to run this board from 3,6V lithium battery (all tested battery is with sufficient constant current of course >2A constant).

**Comment by LilyGO** [comment]
When will you appear, can you send a video to see?
