### ISSUE TITLE
Wrong schematic! Please update it! 

### ISSUE THREAD

**Issue by Nefarious19** [Xinyuan-LilyGO/LilyGo-T-PCIE#13]
Schematic is outdated. For example there is no modem  wwan led on the board or it's not connected. Please update schematic!

**Comment by randybb** [comment]
People are asking for updated schematics and they are just ignoring it.

Anyway, this whole board is so badly designed. They haven't used the whole potential of axp192 for powering modem or other peripherals and there is no way to tap the other not connected DCDC/LDO (at least they could connect these to test points). As they are selling the modem to end users they have to provide firmware updates - never responded to me. Totally waste of money. RAK WisBlock or the newest Particle B series (B524) / Tracker One (ONE524MEA) is much better option...

**Comment by LilyGO** [comment]
The schematic has been updated, if you have any further questions, feel free to contact
