### ISSUE TITLE
Unable to use CAN

### ISSUE THREAD

**Issue by zeljkoavramovic** [Xinyuan-LilyGO/LilyGo-T-PCIE#15]
It seams that ESP32 has fixed pins GPIO4 and GPIO5 for CANH and CANL. I wanted to connect them to SN65HVD230 for logging car OBDII CAN messages, but it seams that in your board GPIO is mapped to M.2.

If my understanding about GPIO5 is correct, could you please fix this in some future revision and let us use CAN?

**Comment by romoloman** [comment]
GPIO5 is free is GPIO4 that is in use for powerkey (for powering on the PCI modem).
I'm using GPIO5 in one of my project and it works perfectly.
You can cut the track from GPIO4 to powerkey and connect to any other free pin if you need it...

**Comment by zeljkoavramovic** [comment]
Thanks, but I've already switched to custom PCB and gave up on LilyGO.
