### ISSUE TITLE
Missing audio decoder chip

### ISSUE THREAD

**Issue by t0bybr** [Xinyuan-LilyGO/LilyGo-T-PCIE#16]
Hi,
I'm thinking about making a basic mobile phone with integrated GPS tracker. Your boards seem to be great for this. Especially the LilyGo T-PCIe. But before ordering I have two questions.

[On this site](https://www.aliexpress.com/item/4001142716386.html?spm=a2g0o.store_pc_groupList.8148356.11.63e736fcVYSjXm) this is stated: *The product does not contain audio decoder chip NAU8810YG* Does that mean it is not possible to make voice calls with this modem?
And I see a Motor connector, is this for a vibration motor?

Thanks in advance.
t0bybr

**Comment by LilyGO** [comment]
Sim868 can make phone calls without decoding chip

**Comment by LilyGO** [comment]
Sim7600 needs decoding chip, there is no default paste, you can ask customer service to add this chip
