### ISSUE TITLE
Board stability with battery

### ISSUE THREAD

**Issue by alextroto** [Xinyuan-LilyGO/LilyGo-T-PCIE#18]
I've tried several boards and all has the same issue:  if it's powered by Li battery, the ESP32 sometimes browns out  when the SIM7600 modem tried to connect to the GSM network. 
Somehow we've improved the situation by adding a 470uF cap on the battery connector, but clearly it's not the best solution.
Anybody had the same issue? Any other ideas to improve the stability of the board?

**Comment by LilyGO** [comment]
Did not encounter this situation, is the lithium battery caused by the problem?
