### ISSUE TITLE
Need AXP192 information and examples

### ISSUE THREAD

**Issue by Stuff4makers** [Xinyuan-LilyGO/LilyGo-T-PCIE#20]
We need full details on the power management IC (AXP192):
- datasheet in English
- example source code on how to communicate between AXP192 and ESP32

You only give us half of the information with this product, this is becoming very frustrating.

**Comment by LilyGO** [comment]
Hello. Refer to this[ library](https://github.com/lewisxhe/AXP202X_Library)
