### ISSUE TITLE
sim7600SA -Update firmware - Issue sim7600E

### ISSUE THREAD

**Issue by McStick0** [Xinyuan-LilyGO/LilyGo-T-PCIE#29]
Hello!
About a year ago I ordered a package ( but due to customs reasons, I did not receive it for a very long time ) which contained ESP32-Wrover-B-AXP192 Pcie+SimCom 7600E Pcie. 

I connected the Pcie as in the tutorial ( [https://github.com/Xinyuan-LilyGO/LilyGo-T-PCIE/blob/master/doc/sim7600SA_update_firmware.md](url) ) but on the computer no SimCom showed up in my device list.
![328031540_698109641860650_2064480967138760048_n](https://user-images.githubusercontent.com/86937384/215334849-b9f3a93a-7672-4b0d-8988-f01d204ebd08.jpg)

![sdsda](https://user-images.githubusercontent.com/86937384/215335142-43057735-e7f3-46a2-8c8f-b986f40ec55e.PNG)

I tested the board for WifiScan, when connected to usb-c the LED on the simcom also lights up.
Any advice? 

edit: Led Status and NetLight shine constantly on SIM7600E

Edit: I used the examples from the package folder named TinyGSM_AllFunctions - when I press reset, nothing happens
I don't know if this is important, but when I press reset, the green LED flashes, but the SimCom Leds are off, until I press the power button - which I guess is the correct response
![image](https://user-images.githubusercontent.com/86937384/215473897-6628db8b-9e10-4380-92a5-28257c2ebe59.png)

**Comment by lewisxhe** [comment]
You are connected incorrectly. DM (D -) and DP (D+) should be directly connected to the D+and D - of the computer instead of USB TO TTL

**Comment by McStick0** [comment]
@lewisxhe 
I understood that a regular USB cable and connect like?:
Red Vcc -- VBus
White Data(+) -- DM
Green Data(-) -- DP
Black GND -- GND

while writing this, I did as I understood - I still see only COM3 and COM4 in the system (some small success )

**Comment by McStick0** [comment]
@lewisxhe
I understood that a regular USB cable and connect like?:
Red Vcc -- VBus
White Data(+) -- DM
Green Data(-) -- DP
Black GND -- GND

while writing this, I did as I understood - I still see only COM3 and COM4 in the system (some small success )

**Comment by McStick0** [comment]
I tried to connect according to this diagram. 
https://docs.espressif.com/projects/esp-at/en/latest/esp32/Get_Started/Hardware_connection.html

Apparently the update went, when I downloaded the ATComandTester for SimCom Modem, and I can't connect to one, and the other is still busy
![image](https://user-images.githubusercontent.com/86937384/216838100-8b957856-d87b-4818-85fd-2e2ecdf84eab.png)

**Comment by McStick0** [comment]
@lewisxhe well, stuck again. Can't click browse.
But step forward, installed driver
![image](https://user-images.githubusercontent.com/86937384/216840129-4860cb2c-4196-45f0-ac5b-f9cc4b40ca3a.png)

**Comment by lewisxhe** [comment]
Try the latest V1.67 tool  
https://1drv.ms/u/s!AmbpOqVezk5dsULM1jyhu4S--GpX?e=uyhSYc

**Comment by McStick0** [comment]
@lewisxhe nope. 
The same thing

**Comment by lewisxhe** [comment]
Please open the compatibility mode test. I have tested that all three computers on my side can work normally. If you can, please replace the computer for test
