### ISSUE TITLE
TinyGSM and support of SIM7070G

### ISSUE THREAD

**Issue by schmeckm** [Xinyuan-LilyGO/LilyGo-T-PCIE#6]
Hi ALL
it seems that LilyGo-T-PCIESIM with 7070G SimCOM Modem is not supported by TinyGSM. 

Do you have a workaround for that or can you recommend another Libary?

Markus

**Comment by LilyGO** [comment]
![image](https://user-images.githubusercontent.com/31160602/131766932-07b70bcd-f52e-426c-9fe2-c48e0f9035cf.png)
https://github.com/vshymanskyy/TinyGSM
