### ISSUE TITLE
pinout diagram question?

### ISSUE THREAD

**Issue by donyoshi** [Xinyuan-LilyGO/LilyGo-T-PCIE#9]
On the pinout diagram, what does the information on the lower right mean?  In particular in regards to the TX/RX pins?

![Hce557a76167d4b498be7789ce54de2eew](https://user-images.githubusercontent.com/56846390/111008606-c3003780-8391-11eb-86df-7ea32b9316dd.jpg)

**Comment by randybb** [comment]
If you want to interact with connected pcie modem, then you need to use mentioned GPIOs: for uart there are pins 26 and 27, then to power this device you need to pull high 25, irq is 36, power button is connected to 4 and status led (if you want to read its status) to 12. Just check example code like this https://github.com/Xinyuan-LilyGO/LilyGo-T-PCIE/blob/master/examples/SIM7600/SIM7600.ino and it should be clear for you.

**Comment by donyoshi** [comment]
Thanks
